channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - future
  - python=3.6
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - Pillow
  - pytorch=1.3
  - torchvision=0.4.1
  - cudatoolkit=10.1
  - pip:
    - pytorch-lightning
    - packaging
